### PR TITLE
Remove .css to silence deprecation warning in sass-rails ~>5.0.1

### PR DESCRIPTION
**Pull request by jbarrieault**
The warning logged when using with Rails 4.2.5 with `sass-rails` `5.0.1`:

```
DEPRECATION WARNING: Extra .css in SCSS file is unnecessary. Rename /opt/rubies/2.2.1/lib/ruby/gems/2.2.0/gems/s3_direct_upload-0.1.7/app/assets/stylesheets/s3_direct_upload_progress_bars.css.scss to /opt/rubies/2.2.1/lib/ruby/gems/2.2.0/gems/s3_direct_upload-0.1.7/app/assets/stylesheets/s3_direct_upload_progress_bars.scss. 
```

### CODE REVIEW

**Comment by mcfiredrill** [comment]
LGTM :+1:

**Comment by mcfiredrill** [comment]
Is this compatible with older rails versions?

**Comment by jbarrieault** [comment]
I believe so, but I haven't tested. I can take a look over the weekend.

Or—since this is the only stylesheet and is very minimal—we could use vanilla CSS and drop the dependency on rails-sass altogether :smiley:

**Comment by mcfiredrill** [comment]
@jbarrieault yeah, there's another PR to drop the dependency on sass. Are we even using any sass features?!

**Comment by jbarrieault** [comment]
The stylesheet does use nesting which is sass. Well worth it to use pure css to lose the dependency!

**Comment by jbarrieault** [comment]
Closing since the dependency on SASS should be dropped all together, IMO. #193 does this, but conflicts need to be resolved.

**Pull request closed without merging**
