### PR TITLE
Add optional DropZone support

### PR DESCRIPTION
**Pull request by dja**

### CODE REVIEW

**Comment by nym** [comment]
I would like to use this.

**Comment by danieljacobarcher** [comment]
@nym It works well for me - just using my own fork, feel free to use it if the pull request is not merged.

**Comment by ilyakatz** [comment]
It worked for me out of the box ...

**Comment by vietntframgia** [comment]
@danieljacobarcher Sorry for inconvenience. I have been problem with `dropzone.js` in s3_direct_upload. Could you explain for me about your way?
My way:
I used `dropzone-rails` gem and your PR code in my project. And I inserted `class dropzone` in s3_uploader_form. I saw `dropzone` made `POST` requests with status 400 when i tried selecting files from my local.

**Comment by andrewjdmccann** [comment]
If anyone runs into this issue and comes across this pull request there's a (somewhat fragile) work around until this PR or similar gets merged. It relies on the fact that `s3_direct_upload` leverages `jQuery-File-Upload` but that's unlikely to change, so this should be pretty safe.

`jQuery-File-Upload` allows you to set some of it's options via `data` attributes.
https://github.com/blueimp/jQuery-File-Upload/wiki/API#data-attributes

```rb
s3_uploader_form(
  # ...
  :data => {
    # ...
    :drop_zone => ".my-dropZone-selector"
  }
)
```

**Comment by thebravoman** [comment]
@amccann the drop_zone data attribute does not work for me. Somehow it is still working for the whole document.

**Comment by thebravoman** [comment]
I've merged the current version of @waynehoover with the dropzone support from @dja. The @dja repo was 20+ commits behind waynehoover and I wanted to use them both.

If anyone needs it - https://github.com/thebravoman/s3_direct_upload

**Pull request closed without merging**
